### ISSUE TITLE
aws region variable should be empty

### ISSUE THREAD

**Issue by VictorLad** [Wefactorit/terraform-aws-eks-module#1]
It could be usefull if aws.region could be empty into "main.tf" file.

Indeed, we can override this value with AWS_DEFAULT_REGION environment variable from CI/CD pipeline variable which will able us to be more flexible in the future.

<img width="174" alt="aws_region" src="https://user-images.githubusercontent.com/51401380/80415507-f00b3f00-88d2-11ea-9479-3ec8a118b65d.png">

**Comment by sype** [comment]
I remove the region from main tf let me know if it's ok

**Comment by VictorLad** [comment]
It works well, I close this issue ;)
